services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app_server:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/home/www/pg_search
    ports:
      - 3001:3000
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
