default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TestPgSearch_development

test:
  <<: *default
  database: TestPgSearch_test

production:
  <<: *default
  database: TestPgSearch_production
  username: TestPgSearch
  password: <%= ENV["TESTPGSEARCH_DATABASE_PASSWORD"] %>
